### ISSUE TITLE
Is it possible to...

### ISSUE THREAD

**Issue by TheRealMrKam** [Malcolm-Q/LC-CleaningCompany#1]
Hello :)
Is it possible to get this "Creatures you kill can be picked up and sold " as a separate mod ? or the ability to desactivate the other features ?

**Comment by Malcolm-Q** [comment]
https://thunderstore.io/c/lethal-company/p/malco/SellBodies/

**Comment by TheRealMrKam** [comment]
Thank you very much :)

edit: just tryed it but i can't interact with the body to grab it anymore

**Comment by aus2004** [comment]
it in fact does not work

**Comment by Malcolm-Q** [comment]
Oh mb I tested it with a hoarder bug and it worked fine. What did you kill? Send your logoutput.log if you can

**Comment by aus2004** [comment]
it should be noted that manticoils and eyeless dogs are killable too, though when me and another friend tried it with a hoarder bug it was not able to be picked up and on my client the hoarder bug appeared to still be alive, despite it being dead.

**Comment by aus2004** [comment]
this could be potentially interference with another mod, but i doubt it because absolutely nothing else does anything with enemies

**Comment by TheRealMrKam** [comment]
> Oh mb I tested it with a hoarder bug and it worked fine. What did you kill? Send your logoutput.log if you can

I tested with hoarding bug too ( on v40) but it works with your cleaning mod, so wierd.

**Comment by bozeeetopic** [comment]
I just came back from playing and had no issues interacting with dead bodies in "SellBodies", so it could really be the fault of a random mod interacting badly.
Secondly I also wanted to ask whether you have plans to add brackens loot since he is also killable (flower petals or dust idk), and spore lizards, as well as outside monsters: birds, baboons, forest guardians and eyeless dogs (I think all of those are killable)
Since most outside threats are too big to be carried, you could add new item for dissecting them and make them into couple of carriable items ( for example eyeless dog = head two handed + torso two handed + limbs and tail as small item)
Awesome mods btw keep up the good work love u man :D

**Comment by aus2004** [comment]
> I just came back from playing and had no issues interacting with dead bodies in "SellBodies", so it could really be the fault of a random mod interacting badly. Secondly I also wanted to ask whether you have plans to add brackens loot since he is also killable (flower petals or dust idk), and spore lizards, as well as outside monsters: birds, baboons, forest guardians and eyeless dogs (I think all of those are killable) Since most outside threats are too big to be carried, you could add new item for dissecting them and make them into couple of carriable items ( for example eyeless dog = head two handed + torso two handed + limbs and tail as small item) Awesome mods btw keep up the good work love u man :D

unrelated but,
forest guardians are not killable, though there is a mod that can potentially make them killable
source: [the wiki](https://lethal-company.fandom.com/wiki/Forest_Keeper)

**Comment by bozeeetopic** [comment]
> unrelated but, forest guardians are not killable, though there is a mod that can potentially make them killable source: [the wiki](https://lethal-company.fandom.com/wiki/Forest_Keeper)

not by the player but I've seen videos in vanilla game where they got eaten by worms, and possibly attacked by swarm of baboons/eyeless dogs, not sure tho.

**Comment by Malcolm-Q** [comment]
> I tested with hoarding bug too ( on v40) but it works with your cleaning mod, so wierd.

Oh yeah it goes without saying that mods built with v45 can have unexpected and inconsistent behaviour on v40

**Comment by Malcolm-Q** [comment]
> ... I also wanted to ask whether you have plans to add brackens loot since he is also killable (flower petals or dust idk), and spore lizards, as well as outside monsters: birds, baboons, forest guardians and eyeless dogs (I think all of those are killable)

Yeah I could add a Bracken item I guess. The cleaning mod does have this. I didn't add dogs and baboons cause yeah it seems ridiculous to carry but I could have them drop a tooth or something.

Not sure when I'll get around to this though I'm gonna be working on v3.0.0 of LGU for a bit here.

**Comment by DwarfWoot** [comment]
Hey, just wanted to add that I also had an issue where Some enemies seemed to be "invincible" (definitely Thumpers were put into a state where they stopped moving, but were still "alive"; and while we managed to kill one Spider, a second one seemed to not be killable). No issues with Hoarding Bugs.

I would upload Logs, but I'm unsure where to find the logoutput.log file

**Comment by TheRealMrKam** [comment]
I just tried in v45 and it seems to works flawlessly even with other mods, Thanks ! :)
