### ISSUE TITLE
[SellBodies Mod] No Shotgun Shell

### ISSUE THREAD

**Issue by DHStyle541** [Malcolm-Q/LC-CleaningCompany#6]
Hi, can you add the Turn On/Off i mean like True/False for monster what can sell and can't sell

and for NutCracker the Weapon Shotgun Flying, and the shotgun shell no drop
maybe next update add the Animations like default then take it the dead body monster [i mean not instant Drop the Monster body and no animations dead monster if this is posibled]

ah y for Crawler,Nutcracker,Spider make it like Holding two Hand not single hand.
and Droping Crawler / Spider weird i mean like not right spot location

**Comment by TonyZeit** [comment]
YES
