### ISSUE TITLE
[Sell Bodies] Desyncing

### ISSUE THREAD

**Issue by ImpulsiveLass** [Malcolm-Q/LC-CleaningCompany#9]
From what I can gather many people are having desyning issues between the client and host that results in bodies vanishing, doubling enemies, attacking and moving while invisible as they are dead, etc.

Maybe there needs to be better checks to determine whats happening serverside? I haven't tested the mod in multiplayer yet but I'd imagine these issues are occurring when everyone has the mod installed since the game shouldn't load in if clients were missing the mod.

**Comment by ImpulsiveLass** [comment]
Ok yes I can confirm all the desyncing issues occur even if everybody in the lobby has the mod installed

**Comment by Miketaviuos** [comment]
Can also confirm. When I kill a monster and try to grab its body its really just a remodeled scrap that has the model of the thing I just killed. So I end up seeing the original monster I just killed on the ground while I have its "body" in my hand, kinda wish the monster when it dies it disappears and the "scrap" that is dropped on the ground or spawns on the ground below it is its body model.

**Comment by ImpulsiveLass** [comment]
I hope the dev reads this. I think they should leave dead enemies alone and just make them spawn a separate scrap item either on death or with the interaction key, maybe just a helpful piece of them.
